name: bahay_kubo
description: A small Flutter game demo for AppDev course â€” "Bahay Kubo".
version: 0.1.0+1
publish_to: "none"
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  audioplayers: ^6.5.1
  image_picker: ^0.8.7+4
  google_fonts: ^4.0.3
  confetti: ^0.7.0
  share_plus: 6.3.3
  screenshot: ^1.3.0
  just_audio: ^0.9.32
  audio_session: ^0.1.25

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/logo.png
    - assets/images/coin.png
    # include all images under assets/images/ (fruit/veg images)
    - assets/images/
    # explicitly include game background assets (ensure bundling)
    - assets/images/gamebg/static.png
    - assets/images/gamebg/clouds.png
    - assets/images/gamebg/treeleft.png
    - assets/images/gamebg/treeright.png
    - assets/images/gamebg/kubo.png


# Configuration for launcher icon generation. Run:
#   flutter pub get ; flutter pub run flutter_launcher_icons:main
# to generate platform launcher icons from `assets/images/logo.png`.
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true

dependency_overrides:
  win32: 5.15.0
